### ISSUE TITLE
Druid在SpringBoot中的使用

### ISSUE THREAD

**Issue by TheWinding** [TheWinding/Articles#13]
Druid是阿里巴巴出品的为监控而生的数据库连接池！

现在Druid有了Springboot专门的starter包，这里来介绍一下一些基础的配置项。

首先导入需要的包
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.1.5</version>
</dependency>
```

然后在resources目录下的application.yml中进行配置

首先，我们先来做数据库链接的配置：
```yml
spring:
  datasource:
    # druid连接池配置
    druid:
      url: jdbc:postgresql://localhost:5432/databaseName
      username: account
      password: password
      driver-class-name: org.postgresql.Driver
      # 初始化大小
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        commons-log:
          data-source-log-enabled: true
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config.decrypt.key: 密文
```
数据库的连接密码通过了Druid进行了加密。

要对密码进行加密，在druid的[官方wiki][1]上有，这里我简单的概述一下。

首先需要找到你下载的druid的jar包，然后执行：

```shell
java -cp druid-xxx.jar com.alibaba.druid.filter.config.ConfigTools you_password
```

需要注意你的druid.jar的版本，然后需要修改you_password为你需要加密的密码。

执行后，会返回给你三个加密后的字符串：

```
privateKey:MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAvSJfr/l4BN0tE9M3psyOi
GmXC+2gnZK7ZGxrabssr1gUrTsSprnaOYIM3Trw/JdhwohIefELJoZZJV9TgSa6bQIDAQABAkBw7z6N2
HvHA76v8NZxPgH6CHrN/5WBoaVNwMOevcpf5ENUQJ7g/FPEkkwe3qS7eekYvzTtbKZVPj/ggqOKAqWtA
iEA8yU3ODI26paIktSvsgkBjn3EkcPRnGnjMQndYWlsWE8CIQDHIijfW4U9iyLDkztDEnH6ogCxIIwlS
vhIxAH7OIVWgwIhANQl3p5bwerBWXyzsnDmxsLrHX4Jm3ScNyzsbIq4D16lAiBvOVA0+UxhhJ5FOK4oF
1xcTjIuvOwqREaLdhdZN0eaewIgaIX2GrCxYfXpBC0Q8qoQOQJvMWnpQ82xeafyuVM3k9g=
```
```
publicKey:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL0iX6/5eATdLRPTN6bMjohplwvtoJ2Su2Rsa2
m7LK9YFK07Eqa52jmCDN068PyXYcKISHnxCyaGWSVfU4Emum0CAwEAAQ==
```
```
password:clYz4f9B9AK6rC4uW8lVW1lY6/aRGYyxNJt6552hXe3zhaQarj9UGsaLW4T+K7zDTXiYUI3
h0WHHPgFM0CBH9w==
```
然后在yml进行配置：
首先设置
```
spring:
  datasource:
    # druid连接池配置
    druid:
      url: jdbc:postgresql://localhost:5432/databaseName
      username: account
      password: 返回的密文
filter:
    config:
        enabled: true
connect-properties:
    config.decrypt: true
    config.decrypt.key: publicKey
```
需要注意.yml的文件需要注意格式，每个key后的value值前面都需要加个空格。

这样就可以加密的你的数据库密码了，在任何时候都强烈推荐这么做。

  [1]: https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
